spring:
  application:
    name: docker-demo
#  datasource:
#    url: jdbc:h2:mem:testdb 
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    hibernate:
    ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#   database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
server:
  port: 8088
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/studentdb
    username: studentuser
    password: studentpass
    driver-class: org.hibernate.dialect.MySQL8Dialect
#    url: jdbc:mysql://mysql-db:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: rootpassword





