spring:
  application:
    name: docker-demo
#  datasource:
#    url: jdbc:h2:mem:testdb 
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
server:
  port: 8088
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: user
    password: password123
    driver-class: org.hibernate.dialect.MySQL8Dialect
#    url: jdbc:mysql://mysql-db:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: rootpassword





